language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.8-dev"
  - "nightly"

services:
  - docker

before_install:
  - docker build -t brunoferreira/minimon .

script:
  - pytest
  - docker run -e CI=true brunoferreira/minimon
